title: tfsec
email: liamgalvin@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Static analysis security scanner for Terraform
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://www.tfsec.dev" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://tfsec.dev"
twitter_username: liam_galvin
github_username:  tfsec
markdown: kramdown

# Build settings
remote_theme: pmarsceill/just-the-docs
logo: "assets/img/logonav.png"
plugins:
  - jekyll-feed


search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 1
  # Maximum amount of previews per search result
  # Default: 3
  previews: 1
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 5
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: false
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false 


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
