# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: tfsec
email: liamgalvin@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Static analysis security scanner for Terraform
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.tfsec.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: liam_galvin
github_username:  tfsec
markdown: kramdown

# Build settings
remote_theme: tfsec/jekyll-doc-theme@gh-pages

bootwatch: simplex

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .idea/*
  - Makefile
  - scripts/*
  - README.md

git_address: https://github.com/tfsec/tfsec
git_edit_address: https://github.com/tfsec/tfsec/blob/master/CONTRIBUTING.md#

defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
